export const myConfiguration = {
    popupClass: '.popup',
    popupAddForm: "#myPopupAdd",
    popupEditForm: "#myPopupEdit",
    popupAvatarForm: "#myPopupAvatar",
    popupImageForm: '#my-popup-image',
    formSelector: '.popup__form',
    labelSelector: '.popup__label',
    inputSelector: '.popup__input',
    addButtonClass: '#btnOpenAdd',
    editButtonClass: '#btn-open-edit',
    submitButtonClass: '.popup__save-button',
    closeButtonClass: 'popup__close-button',
    openedPopupClass: 'popup_opened',
    inactiveButtonClass: 'popup__save-button_inactive',
    inactiveTrashClass: 'elements__trash_inactive',
    addCardButtonClass: '.popup__save-button-add-card',
    inputInvalidSelector: 'popup__input_invalid',
    inputErrorSelector: 'popup__input_error_active',
    cardsContainerClass: '.elements',
    cardTemplateSelector: '#card-template',
    elementsCardSelector: '.elements__card',
    elementImageSelector: '#element-image',
    elementsImageSelector: '.elements__image',
    elementsTitleSelector: '.elements__title',
    elementsLikeSelector: '.elements__like',
    elementsLikeActiveClass: 'elements__like_active',
    elementsLikeCountClass: '.elements__like-counter',
    deleteButton: '#delete-button',
    avatarButton: '#avatar-image',
    profileInfoClass: '.profile__info',
    profileAuthorSelector: '.profile__author',
    profileAboutSelector: '.profile__about',
    profileAvatarSelector: '.profile__avatar',
    editProfileAuthorInput: '#edit-profile-name',
    editProfileAboutInput: '#edit-profile-title',
    createButtonLabel: 'Создать',
    progressButtonLabel: 'Сохранение...',
    saveButtonLabel: 'Сохранить',
    apiConfig: {
        baseUrl: 'https://nomoreparties.co/v1/plus-cohort-18',
        headers: {
            authorization: '63492307-542e-4f00-8b8a-a7276b6e840e',
            'Content-Type': 'application/json'
        }
    },
    id: undefined,
}